import torch


def _axis_tensor(values, sim):
    """Convert coordinate values to a real tensor on the simulation device."""
    sim_dtype = getattr(sim, "_dtype", None)
    if sim_dtype == torch.complex64:
        dtype = torch.float32
    elif sim_dtype == torch.complex128:
        dtype = torch.float64
    else:
        dtype = None

    return torch.as_tensor(values, dtype=dtype, device=getattr(sim, "_device", None))


def _cell_step(cells, axis_name):
    """Return the width of adjacent, equally sized cells from their centers."""
    if cells.ndim != 1:
        raise ValueError(
            f"{axis_name} must be a one-dimensional array of cell centers."
        )
    if cells.numel() < 2:
        raise ValueError(
            f"{axis_name} must contain at least two adjacent cell centers so the "
            "cell width can be inferred."
        )

    spacing = cells[1:] - cells[:-1]
    step = spacing[0]
    if torch.any(spacing <= 0) or not torch.allclose(
        spacing, torch.full_like(spacing, step)
    ):
        raise ValueError(
            f"{axis_name} must contain strictly increasing, equally spaced centers "
            "of adjacent cells."
        )

    return step


def poynting_flux(
    sim,
    layer,
    x_points=None,
    y_points=None,
    z_prop=0.0,
    *,
    x_cells=None,
    y_cells=None,
):
    """
    Compute the z-directed Poynting flux through an XY plane.

    Coordinates can be supplied in one of two mutually exclusive forms:

    * ``x_points`` and ``y_points`` are actual sampling coordinates. The flux
      is integrated with the trapezoidal rule between the first and last point
      on each axis.
    * ``x_cells`` and ``y_cells`` are centers of adjacent, equally sized cells.
      Each field sample represents the full cell around its center, so midpoint
      quadrature is used: ``sum(Sz) * dx * dy``.

    The cell form is appropriate for the cell-centered grids generated by
    :class:`solwa.geometry`. Passing only a contiguous subset of those centers
    integrates only the corresponding subset of cells.

    Parameters
    ----------
    sim : object
        Simulation object providing the ``poynting_xy`` method.
    layer : int
        Index of the layer for which to evaluate the Poynting flux. Use -1 for
        the input interface.
    x_points, y_points : array-like or torch.Tensor, optional
        Actual x/y sampling coordinates for trapezoidal integration. Both must
        be provided together and cannot be mixed with ``x_cells``/``y_cells``.
    z_prop : float, optional
        z-position at which to evaluate the Poynting flux. Default is 0.0.
    x_cells, y_cells : array-like or torch.Tensor, optional
        Centers of adjacent, equally sized x/y cells for midpoint quadrature.
        Both must be provided together and cannot be mixed with point axes.

    Returns
    -------
    torch.Tensor
        Scalar tensor containing the integrated z-component of the Poynting
        vector.

    Raises
    ------
    ValueError
        If point and cell coordinates are mixed, an axis pair is incomplete,
        or cell centers are not suitable for inferring a cell width.
    """
    has_points = x_points is not None or y_points is not None
    has_cells = x_cells is not None or y_cells is not None

    if has_points and has_cells:
        raise ValueError(
            "Use either x_points/y_points or x_cells/y_cells, not a mix of both."
        )
    if not has_points and not has_cells:
        raise ValueError(
            "Provide either x_points/y_points or x_cells/y_cells for integration."
        )

    if has_points:
        if x_points is None or y_points is None:
            raise ValueError("x_points and y_points must be provided together.")
        x_axis = _axis_tensor(x_points, sim)
        y_axis = _axis_tensor(y_points, sim)
    else:
        if x_cells is None or y_cells is None:
            raise ValueError("x_cells and y_cells must be provided together.")
        x_axis = _axis_tensor(x_cells, sim)
        y_axis = _axis_tensor(y_cells, sim)

    if x_axis.ndim != 1 or y_axis.ndim != 1:
        raise ValueError("Poynting-flux integration axes must be one-dimensional.")

    Sz = sim.poynting_xy(layer, x_axis, y_axis, z_prop=z_prop)[2]

    if has_cells:
        dx = _cell_step(x_axis, "x_cells")
        dy = _cell_step(y_axis, "y_cells")
        return Sz.sum() * dx * dy

    return torch.trapezoid(torch.trapezoid(Sz, y_axis, dim=1), x_axis, dim=0)
